name: Update NRFI Model

on:
  workflow_dispatch:  # Allow manual runs
  schedule:
    - cron: "0 11,15 * * *"  # Runs 11 AM and 3 PM UTC (~6 AM & 10 AM ET)

jobs:
  update-nrfi-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run NRFI Model
        run: python update_models.py

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add nrfi_model.csv
          git commit -m "Automated NRFI model update"
          git push
